version: '3'

services:
  borg-backup1:
    env_file:
      - .env
    #environment:
    #- borg_passphrase=${DOCKER_BORG_PASSPHRASE}
    #- destination_path=${DOCKER_BORG_DEST_PATH}
    #- borgUser_passwd=${DOCKER_BORG_USER_PASSWD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        keyDir: ./borg-creds/1
    container_name: borg-backup1
    ports:
      - "2222:22"
    volumes:
      - ./sourceDir/1:/sourceDir:ro
      - ./destDir/1:${DOCKER_BORG_DEST_PATH}:rw
    networks:    
      my_network:
        ipv4_address: 172.100.0.11

  borg-backup2:
    env_file:
      - .env
    #environment:
    #- borg_passphrase=${DOCKER_BORG_PASSPHRASE}
    #- destination_path=${DOCKER_BORG_DEST_PATH}
    #- borgUser_passwd=${DOCKER_BORG_USER_PASSWD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        keyDir: ./borg-creds/2
    container_name: borg-backup2
    ports:
      - "2223:22"
    volumes:
      - ./sourceDir/2:/sourceDir:ro
      - ./destDir/2:/destDir:rw
    networks:
      my_network:
        ipv4_address: 172.100.0.12

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
