version: '3'

services:
  borg-backup:
    container_name: borg-backup
    env_file:
      - private/.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KEY_DIR: ./private
        BACKUP_TARGET_ADDRESS: remote.target.adsfasdfasdfasdfa.com
    #ports:
    #  - "2222:22"
    #volumes:
    #  - ./sourceDir/1:/sourceDir:ro
    #  - ./destDir/1:/destDir:rw
