version: '3'

services:
  borg-backup1:
    extends:
      file: ../docker-compose.yml
      service: borg-backup
    container_name: borg-backup1
    build:
      args:
        KEY_DIR: testPair/private/secrets1/sshKeys
        BORG_PASSPHRASE_FILE: testPair/private/secrets1/borgPassphrase.txt
        BORG_USER_PASSWORD_FILE: testPair/private/secrets1/borgUserPass.txt
        BORG_SSH_PASSPHRASE_FILE: testPair/private/secrets1/borgSshPassphrase.txt
        BACKUP_TARGET_ADDRESS: 172.100.0.12
        BACKUP_NAME: auto-backup-1
        BACKUP_FREQUENCY: "* * * * *"
        BORG_UID: 7654
        BORG_GID: 7654

    volumes:
      - ./sourceDir1:/sourceDir:ro
      - ./destDir1:/destDir:rw
      - ./logs/1:/var/log:rw
    networks:
      borg-test-network:
        ipv4_address: 172.100.0.11

  borg-backup2:
    extends:
      file: ../docker-compose.yml
      service: borg-backup
    container_name: borg-backup2
    build:
      args:
        KEY_DIR: testPair/private/secrets2/sshKeys
        BORG_PASSPHRASE_FILE: testPair/private/secrets2/borgPassphrase.txt
        BORG_USER_PASSWORD_FILE: testPair/private/secrets2/borgUserPass.txt
        BORG_SSH_PASSPHRASE_FILE: testPair/private/secrets2/borgSshPassphrase.txt
        BACKUP_TARGET_ADDRESS: 172.100.0.11
        BACKUP_NAME: auto-backup-2
        BORG_UID: 7654
        BORG_GID: 7654
    volumes:
      - ./sourceDir2:/sourceDir:ro
      - ./destDir2:/destDir:rw
      - ./logs/2:/var/log:rw
    networks:
      borg-test-network:
        ipv4_address: 172.100.0.12

networks:
  borg-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24

